branch-defaults:
  default:
    environment: production
    group_suffix: null
global:
  application_name: vantagepoint-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 22
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
